const savedProjects=[];
const drawer=document.querySelector('#drawer'),content=document.querySelector('#drawer-content'),toast=document.querySelector('#toast'),sb=window.supabaseClient;
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function money(value){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0))}
function bindImageFallbacks(root=document){
  root.querySelectorAll('img').forEach(img=>{
    if(img.dataset.fallbackBound) return;
    img.dataset.fallbackBound='1';
    img.addEventListener('error',()=>{
      if(img.dataset.imageFailed) return;
      img.dataset.imageFailed='1';
      img.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1400 1000"><rect width="1400" height="1000" fill="#e8e5df"/><text x="700" y="500" text-anchor="middle" dominant-baseline="middle" fill="#777" font-family="Arial,sans-serif" font-size="34">webdev preview</text></svg>');
    },{once:false});
  });
}
function catalogImage(site){return site.image||'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=88'}
async function renderFeaturedProducts(){
 const grid=document.querySelector('#featured-products'); if(!grid||!sb)return;
 const {data,error}=await sb.from('website_listings').select('id,name,category,price,image,description,published').eq('published',true).order('id').limit(8);
 if(error){console.error(error);grid.innerHTML='<div class="empty-state">Catalog temporarily unavailable. <a href="websites.html">Open the full catalog ↗</a></div>';return}
 if(!data?.length){grid.innerHTML='<div class="empty-state">No published websites yet. <a href="websites.html">Open catalog ↗</a></div>';return}
 grid.innerHTML=data.map((site,i)=>'<article class="product"><div class="product-media"><img src="'+escapeHtml(catalogImage(site))+'" alt="'+escapeHtml(site.name)+' website preview" loading="lazy"><button class="wish" aria-label="Save '+escapeHtml(site.name)+'">♡</button><span>'+escapeHtml(site.category)+'</span></div><div class="product-info"><div><h3>'+escapeHtml(site.name)+'</h3><p>'+escapeHtml(site.description||'Ready-to-customize website')+'</p></div><strong>'+String(i+1).padStart(2,'0')+'</strong></div><div class="product-price-row"><strong>'+money(site.price)+'</strong><span>Ready to customize</span></div><a class="add product-link" href="client.html?website='+encodeURIComponent(site.id)+'">View website <span>↗</span></a></article>').join('');
 bindImageFallbacks(grid);
 grid.querySelectorAll('.wish').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='♡'?'♥':'♡';b.style.transform='scale(1.18)';setTimeout(()=>b.style.transform='',180)});
}
async function sendContact(payload){if(!sb)return{error:{message:'Service unavailable'}};return await sb.from('contact_requests').insert(payload)}
function openDrawer(type){drawer.classList.add('open');if(type==='contact')content.innerHTML='<h2>Start a project</h2><p>Tell us what you need and we will shape the right website direction around your business.</p><input id="dName" placeholder="Your name"><input id="dCompany" placeholder="Business / company"><input id="dEmail" placeholder="Email address" type="email"><textarea id="dMessage" placeholder="What do you need the website to do?"></textarea><button class="btn dark" id="sendDrawer" style="width:100%;margin-top:10px">Send project enquiry ↗</button><small id="drawerMsg"></small>';if(type==='search')content.innerHTML='<h2>Explore webdev</h2><input id="searchInput" placeholder="Search services or website types…" autofocus><p style="color:#777">Explore websites for sale, e-commerce, business websites, SaaS, booking sites and custom builds.</p><a class="btn dark" href="websites.html" style="width:100%;margin-top:10px">Browse website catalog ↗</a>';if(type==='account')content.innerHTML='<h2>Client / Owner access</h2><p>Clients use the secure workspace. Owners use the private marketplace dashboard.</p><a class="btn dark" href="client.html" style="width:100%;margin-top:10px">Client area ↗</a><a class="btn light" href="login.html" style="width:100%;margin-top:10px">Owner login ↗</a>';if(type==='menu')content.innerHTML='<h2>Menu</h2><p><a href="websites.html">Websites for sale ↗</a></p><p><a href="#services">Services</a></p><p><a href="#process">Process</a></p><p><a href="#about">About</a></p><p><a href="#contact">Start a project</a></p>';const send=document.querySelector('#sendDrawer');if(send)send.onclick=async()=>{const msg=document.querySelector('#drawerMsg');const payload={name:document.querySelector('#dName').value.trim(),company:document.querySelector('#dCompany').value.trim(),email:document.querySelector('#dEmail').value.trim(),message:document.querySelector('#dMessage').value.trim()};if(!payload.email||!payload.message){msg.textContent='Email and project details are required.';return}const {error}=await sendContact(payload);msg.textContent=error?error.message:'Enquiry received. We will follow up from the project workspace.';if(!error)setTimeout(()=>drawer.classList.remove('open'),1200)}}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.open)));if(document.querySelector('.close'))document.querySelector('.close').onclick=()=>drawer.classList.remove('open');if(drawer)drawer.onclick=e=>{if(e.target===drawer)drawer.classList.remove('open')};document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{savedProjects.push(b.dataset.project);toast.textContent=b.dataset.project+' added to your shortlist.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});document.querySelectorAll('.wish').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='♡'?'♥':'♡';b.style.transform='scale(1.18)';setTimeout(()=>b.style.transform='',180)});const quotes=['“Your website should make the value of your business obvious before the visitor has to think.”','“A premium website is a business tool: clear positioning, strong presentation and a direct path to action.”','“The goal is not to look like everyone else. The goal is to look unmistakably right for your business.”'];let qi=0;const q=document.querySelector('#quote');if(q){document.querySelector('.next').onclick=()=>{qi=(qi+1)%quotes.length;q.innerHTML=quotes[qi]+'<cite>— webdev principle</cite>'};document.querySelector('.prev').onclick=()=>{qi=(qi-1+quotes.length)%quotes.length;q.innerHTML=quotes[qi]+'<cite>— webdev principle</cite>'}}const form=document.querySelector('#newsletter');if(form)form.onsubmit=async e=>{e.preventDefault();const email=form.querySelector('input').value.trim();const {error}=await sendContact({email,message:'Website project enquiry from homepage newsletter form.'});document.querySelector('#newsmsg').textContent=error?error.message:'Thanks. Your project enquiry has been received.';if(!error)e.target.reset()};
renderFeaturedProducts();
bindImageFallbacks(document);
